name: Build Packages

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos', image: 'macos-latest' },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'  # Specify your Node.js version

      - name: Prebuild step                                                      
        if: matrix.os.name == 'linux'                                           
        run: apt install flatpak flatpak-builder elfutils && flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo 
          
      - name: Install dependencies
        run: npm install

      - name: Publish binaries
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
